### ISSUE TITLE
Crash in for loop with conditionals that use variables

### ISSUE THREAD

**Issue by ryankaplan** [evanw/glslx#17]
The following relatively simple shader crashes the compiler for me. Making either `start` or `stop` a float literal seems to fix the issue.

```
export void textureFragment() {
  float start = 1.0;
  float stop = 2.0;
  for (float t = start; t < stop;) { }
}
```

**Comment by evanw** [comment]
Thanks for reporting this issue, and sorry for the crash. Should be fixed now. Let me know if you are still experiencing issues.

**Comment by ryankaplan** [comment]
Thaaaaanks!! :)
