### ISSUE TITLE
Support `import` in GLSLX code

### ISSUE THREAD

**Issue by james-pre** [evanw/glslx#21]
I've been using GLSLX for a few days and it is amazing. I'm running into an issue where I would like to have some code modularity (between files), and do not want to use a rendering engine like Babylon or Three to create multiple materials using the different shader code and send variables between them. Would it be possible to support `import`? Here is a simple idea for the syntax (ESM style):

random.glslx
```glsl
precision highp float;

export float random(vec2 seed) {
    return fract(cos(dot(seed.xy, vec2(12.9898, 78.233))) * 43758.5453);
}
```

shader.glslx
```glsl
precision highp float;

import { random } from './random';

uniform vec2 seed;

export void fragment(){
    gl_FragColor = vec3(random(seed));
}
```

GLSLX imports in GLSLX can be handled like GLSLX imports in Typescript by having a .d.ts declaration to go with the .glslx shader.

**Comment by evanw** [comment]
There is actually already a way to import other files. You can use `#include` to do that, which behaves similarly to `#include` in C/C++ except that each file is only imported at most once (so you don't need header guards). Note that you don't need to explicitly `export` things from the imported file.
