### ISSUE TITLE
Question: instead of returning "renaming" return a dictionary in all cases

### ISSUE THREAD

**Issue by psulat** [evanw/glslx#5]
Evan,

Have you considered returning a dictionary/mapping of variables, regardless if renaming is done or not?  For example, returning the following when no renaming is done.

map = {
    image: "image",
    loopCnt: "loopCnt"
}

That way the output result is better abstracted and the interfacing code has no idea if the code was minimized or not.  Currently, the interfacing code has to interpret the renaming value and decide what to do.

Pete

**Comment by evanw** [comment]
Yup I've been meaning to do that. Thanks for the reminder!
